# logging config
logging:
  config: classpath:logback-spring.xml

#mybatis config
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml

# spring config
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2&autoReconnect=true
    username: root
    password: 'lji39220922'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2&autoReconnect=true
    username: root
    password: 'lji39220922'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
